import { Model } from "@/types/interfaces";

export const models: Model[] = [
  {
    value: "tiny",
    label: "Tiny",
    description: "Fastest",
    size: "80MB",
    ram: "1GB",
    details: "Lightweight and fast. Good for simple audio and low-resource devices.",
    isDownloaded: false,
  },
  {
    value: "tiny.en",
    label: "Tiny (EN)",
    description: "Fastest for English",
    size: "80MB",
    ram: "1GB",
    details: "Lightweight and fast. Good for simple audio, with enhanced English accuracy.",
    isDownloaded: false,
  },
  {
    value: "base",
    label: "Base",
    description: "General use",
    size: "150MB",
    ram: "1GB",
    details: "Reliable for everyday transcription with good speed and accuracy.",
    isDownloaded: false,
  },
  {
    value: "base.en",
    label: "Base (EN)",
    description: "General use for English",
    size: "150MB",
    ram: "1GB",
    details: "Reliable for everyday transcription, with enhanced English accuracy.",
    isDownloaded: false,
  },
  {
    value: "small",
    label: "Small",
    description: "Balanced",
    size: "480MB",
    ram: "2GB",
    details: "Better accuracy than smaller models. Good for varied accents and conditions.",
    isDownloaded: false,
  },
  {
    value: "small.en",
    label: "Small (EN)",
    description: "Balanced for English",
    size: "480MB",
    ram: "2GB",
    details: "Better accuracy than smaller models, with enhanced English performance.",
    isDownloaded: false,
  },
  {
    value: "medium",
    label: "Medium",
    description: "Accurate",
    size: "1.5GB",
    ram: "5GB",
    details: "High accuracy for challenging audio. A balanced precision choice.",
    isDownloaded: false,
  },
  {
    value: "medium.en",
    label: "Medium (EN)",
    description: "Accurate for English",
    size: "1.5GB",
    ram: "5GB",
    details: "High accuracy for challenging audio, with enhanced English precision.",
    isDownloaded: false,
  },
  {
    value: "large-v3-turbo",
    label: "Large (Turbo)",
    description: "Fast & Accurate",
    size: "1.6GB",
    ram: "6GB",
    details: "Near-Large accuracy at significantly higher speed.",
    isDownloaded: false,
  },
  {
    value: "large-v3",
    label: "Large",
    description: "Max accuracy",
    size: "3.1GB",
    ram: "10GB",
    details: "Most accurate. Best for complex audio or many speakers. Requires lots of RAM.",
    isDownloaded: false,
  },
];
